"""baseline schema: clinical tables + auth

Revision ID: 734e508c26bf
Revises: 
Create Date: 2026-07-20 21:31:11.886992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734e508c26bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_joint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rest_threshold', sa.Float(), nullable=False),
    sa.Column('work_threshold', sa.Float(), nullable=False),
    sa.Column('target_rom_min', sa.Float(), nullable=False),
    sa.Column('target_rom_max', sa.Float(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'therapist', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('authtoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sa.Enum('email_verify', 'password_reset', name='tokenpurpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authtoken_token_hash'), 'authtoken', ['token_hash'], unique=True)
    op.create_index(op.f('ix_authtoken_user_id'), 'authtoken', ['user_id'], unique=False)
    op.create_table('referenceprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_reps', sa.Integer(), nullable=False),
    sa.Column('seq_len', sa.Integer(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=True),
    sa.Column('mean_trajectory', sa.JSON(), nullable=True),
    sa.Column('std_trajectory', sa.JSON(), nullable=True),
    sa.Column('ml_threshold', sa.Float(), nullable=True),
    sa.Column('ml_model_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_start_sec', sa.Float(), nullable=True),
    sa.Column('ref_end_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referenceprofile_exercise_id'), 'referenceprofile', ['exercise_id'], unique=False)
    op.create_table('rehabsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('average_rom', sa.Float(), nullable=True),
    sa.Column('maximum_rom', sa.Float(), nullable=True),
    sa.Column('minimum_rom', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('pain_score', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('average_knee_angle', sa.Float(), nullable=True),
    sa.Column('average_hip_angle', sa.Float(), nullable=True),
    sa.Column('average_shoulder_angle', sa.Float(), nullable=True),
    sa.Column('average_elbow_angle', sa.Float(), nullable=True),
    sa.Column('average_ankle_angle', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('posture_mistakes', sa.JSON(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rehabsession_date'), 'rehabsession', ['date'], unique=False)
    op.create_index(op.f('ix_rehabsession_exercise'), 'rehabsession', ['exercise'], unique=False)
    op.create_index(op.f('ix_rehabsession_patient_id'), 'rehabsession', ['patient_id'], unique=False)
    op.create_table('therapistprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapistprofile_user_id'), 'therapistprofile', ['user_id'], unique=True)
    op.create_table('exercisefeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['rehabsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercisefeedback_session_id'), 'exercisefeedback', ['session_id'], unique=False)
    op.create_table('jointmeasurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('knee_angle', sa.Float(), nullable=True),
    sa.Column('hip_angle', sa.Float(), nullable=True),
    sa.Column('shoulder_angle', sa.Float(), nullable=True),
    sa.Column('elbow_angle', sa.Float(), nullable=True),
    sa.Column('ankle_angle', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['rehabsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jointmeasurement_session_id'), 'jointmeasurement', ['session_id'], unique=False)
    op.create_table('patientprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('therapist_id', sa.Uuid(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('injury_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('injury_date', sa.Date(), nullable=True),
    sa.Column('injury_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recovery_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_program', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapistprofile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patientprofile_therapist_id'), 'patientprofile', ['therapist_id'], unique=False)
    op.create_index(op.f('ix_patientprofile_user_id'), 'patientprofile', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patientprofile_user_id'), table_name='patientprofile')
    op.drop_index(op.f('ix_patientprofile_therapist_id'), table_name='patientprofile')
    op.drop_table('patientprofile')
    op.drop_index(op.f('ix_jointmeasurement_session_id'), table_name='jointmeasurement')
    op.drop_table('jointmeasurement')
    op.drop_index(op.f('ix_exercisefeedback_session_id'), table_name='exercisefeedback')
    op.drop_table('exercisefeedback')
    op.drop_index(op.f('ix_therapistprofile_user_id'), table_name='therapistprofile')
    op.drop_table('therapistprofile')
    op.drop_index(op.f('ix_rehabsession_patient_id'), table_name='rehabsession')
    op.drop_index(op.f('ix_rehabsession_exercise'), table_name='rehabsession')
    op.drop_index(op.f('ix_rehabsession_date'), table_name='rehabsession')
    op.drop_table('rehabsession')
    op.drop_index(op.f('ix_referenceprofile_exercise_id'), table_name='referenceprofile')
    op.drop_table('referenceprofile')
    op.drop_index(op.f('ix_authtoken_user_id'), table_name='authtoken')
    op.drop_index(op.f('ix_authtoken_token_hash'), table_name='authtoken')
    op.drop_table('authtoken')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
